# profile file for using dbt core commands in github actions

BasketIntelligenceModel:
  target: dev
  outputs:
    dev:
      dataset: BasketIntelligence
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ./creds.json
      location: europe-west3
      method: service-account
      priority: interactive
      project: keen-vial-420113
      threads: 1
      type: bigquery
