
version: 2

models:
  - name: dim_position
    description: "Schema for the dimension table position"
    columns:
      - name: pos
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
          - accepted_values:
              values: ['C','PF','SF','SG','PG']

  - name: dim_player_team
    description: "Schema for the dimension table position"
    columns:
      - name: player_team
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  
  - name: fact_player_stats
    description: "Schema for the fact table player stats"
    columns:
      - name: player_ID
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null