name: Run dbt on BigQuery using mwhitaker/dbt-action

on:
  push:
    branches: ["main"]

jobs:
  run_dbt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: dbt-action
      id: dbt-run
      uses: mwhitaker/dbt-action@master
      with:
        dbt_command: "dbt run --profiles-dir ."
      env:
        DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}
        
    - name: Get the result
      if: ${{ always() }}
      run: echo "${{ steps.dbt-run.outputs.result }}"
      shell: bash
