
name: Run dbt on BigQuery

on:
  push:
    branches: none
    #branches: [ "main" ] # Specify the branches to trigger the workflow

jobs:
  run_dbt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' # Choose your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-bigquery

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: '{{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account_file: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}'

      - name: Run dbt commands
        run: |
          dbt deps 
          dbt seed 
          dbt run 
          dbt test 
          dbt docs generate
